#!/bin/bash
# Script for connecting my Local Digipeater DB0HFT running Xnet
#
# after connecting DB0HFT with axcall i can get my Hamnet IP
# with command 'getip'
#
# Change MY_CALL below to your Callsign, same as in axports
# Change MY_IP to the IP you got from the Digipeater

MY_CALL=MYCALL-1
MY_IP=44.149.140.55
SER_KISS=/dev/ttyUSB0


PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/usr/sbin:/etc/ax25:/usr/local/ax25
case "$1" in
  start)
    kissattach $SER_KISS ax0 > /tmp/ax25-config.tmp
    
    #echo 1 > /proc/sys/net/ax25/ax0/ip_default_mode

    # experimental Parameters, maybe only for direct Links?
    #echo 7 >/proc/sys/net/ax25/ax0/standard_window_size
    #echo 100 >/proc/sys/net/ax25/ax0/t1_timeout
    #echo 30 >/proc/sys/net/ax25/ax0/t2_timeout
    #echo 30000 >/proc/sys/net/ax25/ax0/t3_timeout
    #echo 30 >/proc/sys/net/ax25/ax0/maximum_retry_count
    
    # https://thomask.sdf.org/blog/2017/08/06/improving-arp-performance-on-slow-ax-25-links.html
    #echo 5000 > /proc/sys/net/ipv4/neigh/ax0/retrans_time_ms
    #echo 1200000 > /proc/sys/net/ipv4/neigh/ax0/base_reachable_time_ms
    
    axparms -route add ax0 db0hft -ipmode vc
    axparms --setcall ax0 ${MY_CALL}
    ip address add ${MY_IP}/32 dev ax0
    
    arp -H ax25 -i ax0 -s 44.149.140.50 db0hft
    
    ip route add 44.149.140.50 dev ax0
    ip route add 44.130.0.0/16 via 44.149.140.50
    ip route add 44.148.0.0/15 via 44.149.140.50
    ip route add 44.224.0.0/15 via 44.149.140.50

    #Blocks outgoing Multicast on our AX Device
    iptables -A OUTPUT -s ${MY_IP}/32 -d 224.0.0.0/4 -j REJECT

  ;;

  stop)
    killall -TERM kissattach
    arp -d 44.149.140.50
    iptables -D OUTPUT -s ${MY_IP}/32 -d 224.0.0.0/4 -j REJECT
    exit 0
  ;;

  *)
    echo "Usage: startax {start|stop}"
    exit 0
  ;;
esac
exit 0
